site_name: Système de Positionnement UWB pour Voitures RC
site_description: Documentation complète du système de chronométrage et positionnement UWB DW3000
site_author: Hugo
# repo_url: https://github.com/hugo/UWB-ESP32
repo_name: UWB-ESP32

theme: readthedocs

# Extensions Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - markdown.extensions.toc:
      permalink: true

# Plugins
plugins:
  - search:
      lang: fr
  - plantuml:
      puml_url: http://www.plantuml.com/plantuml/
      output_format: svg
      num_workers: 8
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago

# Navigation
nav:
  - Accueil: index.md
  - Vision & Objectifs: vision.md
  - Vue Globale: global.md
  

extra_css:
  - stylesheets/extra.css
